spring:
  application:
    name: green-connect-api
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: sqlserver
      mode: always
